jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'

    variables:
      YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages
      - script: |
          yarn --frozen-lockfile
        displayName: 'yarn'
      - script: |
          yarn lint
        displayName: 'yarn lint'
      - script: |
          yarn test:unit
        displayName: 'yarn test:unit'
      - script: |
          yarn build
        displayName: 'yarn build'
