jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
        displayName: 'npm install'
      - script: |
          npm run lint
        displayName: 'npm lint'
      - script: |
          npm run test:unit
        displayName: 'npm test:unit'
      - script: |
          npm run test:e2e
        displayName: 'npm test:e2e'
      - script: |
          npm run build
        displayName: 'npm build'
